# Site settings
title: Emrah Bostan
email: bostan@berkeley.edu
description: "Emrah Bostan, University of Amsterdam"
baseurl: ""
url: "https://emrahbostan.com/"

analyticsID: "UA-25317383-1"

# Build settings
markdown: kramdown
permalink: pretty
production: true

exclude:
  - bower_components
  - node_modules
  - package.json
  - bower.json
  - Gruntfile.js
  - README.md
  - setup
